In [4]:
import os
import sys
from importlib import reload

sys.path.append('../src')

import mix
import torch

In [15]:
x = torch.tensor([[0,1],
                 [0,1],
                 [0,1],
                 [0,1],
                 [0,1],
                 [0,1],
                 [0,1],
                 [1,0],
                 [1,0],
                 [1,0],
                 [1,0],
                 [1,0],
                 [1,0],
                 [1,0],
                 [1,0],]
                )
x

tensor([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]])

In [16]:
reload(mix)
mixup = mix.Mixup()

In [18]:
mixup(x)

tensor([[8.3067e-03, 9.9169e-01],
        [2.8268e-01, 7.1732e-01],
        [3.3389e-01, 6.6611e-01],
        [0.0000e+00, 1.0000e+00],
        [0.0000e+00, 1.0000e+00],
        [0.0000e+00, 1.0000e+00],
        [2.8399e-03, 9.9716e-01],
        [1.0000e+00, 0.0000e+00],
        [9.9988e-01, 1.1861e-04],
        [8.1798e-01, 1.8202e-01],
        [1.0000e+00, 0.0000e+00],
        [1.0000e+00, 0.0000e+00],
        [1.0000e+00, 0.0000e+00],
        [9.9989e-01, 1.1009e-04],
        [9.4692e-01, 5.3079e-02]])

In [174]:
reload(mix)
cutmix = mix.Cutmix(continuous=False)

In [175]:
x = (torch.rand(4,100) * 10).long()
x

tensor([[0, 9, 3, 1, 9, 2, 6, 2, 7, 0, 7, 2, 1, 1, 7, 9, 1, 4, 0, 3, 4, 8, 5, 7,
         5, 0, 7, 1, 9, 6, 5, 3, 8, 3, 1, 6, 9, 2, 0, 6, 7, 6, 1, 2, 5, 0, 3, 3,
         8, 1, 1, 8, 7, 0, 3, 1, 7, 0, 8, 7, 4, 0, 8, 0, 8, 0, 7, 0, 1, 1, 5, 8,
         2, 7, 5, 4, 2, 3, 2, 7, 9, 3, 8, 9, 4, 0, 6, 3, 7, 6, 9, 1, 0, 6, 5, 1,
         1, 2, 5, 6],
        [6, 3, 4, 1, 3, 9, 1, 5, 3, 4, 7, 4, 7, 4, 8, 5, 7, 0, 5, 9, 6, 7, 0, 0,
         2, 3, 1, 0, 2, 4, 7, 8, 3, 6, 5, 2, 1, 5, 1, 2, 9, 6, 2, 0, 4, 9, 5, 4,
         0, 8, 1, 3, 7, 5, 0, 1, 4, 3, 4, 1, 4, 6, 9, 4, 1, 9, 1, 0, 9, 9, 9, 2,
         9, 2, 5, 5, 1, 1, 7, 9, 1, 8, 0, 5, 2, 6, 4, 9, 2, 2, 4, 4, 8, 3, 6, 5,
         3, 2, 4, 4],
        [7, 5, 7, 2, 1, 7, 1, 7, 1, 5, 0, 7, 2, 8, 4, 3, 0, 5, 1, 6, 5, 2, 6, 7,
         6, 1, 8, 4, 9, 7, 6, 9, 2, 0, 8, 5, 2, 1, 5, 3, 4, 5, 8, 5, 6, 4, 6, 7,
         6, 9, 0, 8, 9, 3, 9, 7, 8, 7, 5, 6, 9, 0, 6, 8, 0, 9, 1, 4, 5, 5, 0, 1,
         0, 7, 8, 1, 5, 2, 2, 8, 7, 7, 3, 9, 8, 8, 2, 9, 1, 8, 0,

In [177]:
cutmix(x)

tensor([[5, 9, 3, 1, 2, 5, 6, 7, 7, 7, 0, 2, 1, 1, 8, 9, 1, 4, 0, 9, 9, 8, 5, 5,
         5, 0, 7, 0, 9, 8, 5, 3, 8, 3, 5, 6, 0, 7, 7, 6, 7, 6, 1, 2, 5, 0, 3, 9,
         8, 1, 1, 0, 7, 0, 3, 0, 1, 0, 8, 1, 9, 2, 1, 0, 8, 0, 7, 5, 5, 1, 5, 8,
         2, 7, 5, 4, 1, 3, 2, 7, 9, 3, 8, 9, 4, 4, 4, 5, 9, 6, 9, 5, 0, 3, 5, 1,
         1, 2, 5, 4],
        [6, 3, 4, 1, 3, 9, 1, 5, 3, 4, 7, 4, 7, 4, 8, 5, 0, 0, 5, 6, 6, 7, 0, 7,
         2, 1, 8, 0, 9, 7, 7, 8, 3, 6, 8, 2, 1, 5, 5, 3, 9, 6, 2, 0, 4, 9, 5, 4,
         0, 8, 1, 3, 7, 3, 0, 1, 4, 7, 4, 1, 4, 6, 9, 4, 1, 9, 1, 0, 9, 9, 9, 2,
         9, 2, 8, 5, 1, 1, 7, 9, 1, 7, 0, 5, 8, 8, 2, 9, 2, 8, 4, 3, 6, 3, 6, 5,
         3, 2, 4, 4],
        [7, 5, 7, 2, 9, 7, 1, 2, 1, 0, 7, 2, 1, 8, 4, 3, 1, 5, 1, 6, 4, 2, 5, 7,
         5, 1, 7, 4, 9, 6, 6, 3, 2, 0, 8, 6, 2, 2, 5, 3, 4, 6, 8, 5, 5, 4, 6, 7,
         6, 1, 0, 8, 9, 3, 3, 7, 8, 7, 5, 6, 9, 0, 6, 0, 8, 9, 1, 0, 5, 5, 0, 8,
         0, 7, 8, 1, 5, 2, 2, 7, 7, 3, 8, 9, 8, 0, 2, 3, 7, 8, 0,

In [178]:
cutmix.lam

tensor([0.6342, 0.7987, 0.6191, 0.9104])

In [179]:
cutmix.mask.shape

torch.Size([4, 100])

In [180]:
cutmix.mask

tensor([[ True, False, False, False,  True,  True, False,  True, False,  True,
          True, False,  True, False,  True, False, False, False, False,  True,
          True,  True, False,  True, False, False, False,  True,  True,  True,
         False, False, False, False,  True, False,  True,  True,  True, False,
         False, False, False, False, False, False, False,  True, False, False,
         False,  True, False, False, False,  True,  True, False, False,  True,
          True,  True,  True, False, False, False, False,  True,  True, False,
         False, False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False,  True,  True,  True,  True, False,
         False,  True, False,  True, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,  True,
         False, False, False,  True, False,  True, 

In [115]:
bool(1)

True

In [106]:
cutmix.lam

tensor([0.9814, 0.7586, 0.9977, 0.6013])

In [108]:
cutmix.mask.sum(1)

tensor([1, 1, 1, 1])